[theme]
primaryColor = "#1E88E5" # Deep blue for medical feel
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#333333"
font = "sans-serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
